### ISSUE TITLE
Custom Commands !

### ISSUE THREAD

**Issue by vishnusure** [mulcmu/home-skainet#4]
Great Project ! kudos ! I am sure to try and report any issues ! Also can I use my own commands in the sdkconfig file ? If so need to figure out international phonetics for my custom commands as next step !

also when I add my own custom
Commands how do I link the relevant action to fire up in home assistant ?

**Comment by mulcmu** [comment]
Here is the info for getting the phonetics for custom commands.  https://github.com/espressif/esp-sr/tree/release/v1.0/tool

For the actions, I had a few automations that trigger on changes to the numeric _Voice Command ID_

**Comment by vishnusure** [comment]
Thank you !
